version: '2'
services:

  reg3_water_flask:
    image: jvicient/reg_water_flask:latest
    hostname: reg3waterflask
    networks:
      - qnet-dhcp
    ports:
      - 80:80
    restart: unless-stopped

  reg3_telegram:
    image: jvicient/reg_telegram:v1.1
    hostname: reg3telegram
    environment:
      - TELEGRAM_TOKEN=#copy the token without ' nor "
      - TELEGRAM_CHAT_ID=#copy the chat id
      - TELEGRAM_ADMIN_ID=#copy the admin id
    networks:
      - qnet-dhcp
    restart: unless-stopped

networks:
  qnet-dhcp:
    driver: qnet
    driver_opts:
      iface: "eth1"
    ipam:
      driver: qnet
      options:
        iface: "eth1"
